---
title: "Teaching"
---


<style>
  .course-description {
    margin-left: 30px; /* Indent to the right */
    /* font-size: medium; */
  }
  a {
    color: #0066cc;
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline; 
  }
</style>

<h2>2026</h2>
<h3>Spring : Probability, Statistics and Data Visualization</h3>
<div class="course-description">
  Professor Incharge: <a href="https://mayank4490.github.io">Mayank Singh</a> <br>
  Course Website: <a href="https://sites.google.com/iitgn.ac.in/es114-2026/home">ES-114: Probability, Statistics and Data Visualization</a> <br>
  <!-- Position : Graduate Teaching Fellow (GTF) <br> -->
  Position : Graduate Teaching Fellow [(GTF)](gtf-position.qmd) <br>
  Taught concepts of probability, statistics, and data visualization using Python to a classroom of 360 students. Conducted weekly lab sessions, assisted in grading assignments, and provided support during exams.
</div>



<h2>2025</h2>
<h3>Fall : Machine Learning</h3>
<div class="course-description">
  Professor Incharge: <a href="https://nipunbatra.github.io/">Nipun Batra</a> <br>
  Course Website: <a href="https://nipunbatra.github.io/ml2025/">ES-335: Machine Learning</a> <br>
  Position : Head Teaching Assistant (TA) <br>
  Designed and graded quizzes, assignments, and viva examinations for a large undergraduate class of 280 students, and contributed to managing instructional logistics.
</div>

<h3>Spring : Probability, Statistics and Data Visualization</h3>
<div class="course-description">
  Professor Incharge: <a href="https://nipunbatra.github.io/">Nipun Batra</a> <br>
  Course Website: <a href="https://nipunbatra.github.io/psdv25/">ES-114: Probability, Statistics and Data Visualization</a> <br>
  Position : Head Teaching Assistant (TA) <br>
  Organised and evaluated quizzes, assignments, took vivas for a classroom of 320 students, while also playing a pivotal role in supporting classroom logistics.
</div>

<h2>2024</h2>
<h3>Spring and Fall : Machine Learning,</h3>
<div class="course-description">
  Professor Incharge: <a href="https://nipunbatra.github.io/">Nipun Batra</a> <br>
  Course Website: <a href="https://nipunbatra.github.io/ml2024-fall/">ES-335: Machine Learning (Fall 2024)</a> ,  <a href="https://nipunbatra.github.io/ml2024/">ES-335: Machine Learning (Spring 2024)</a> <br>
  Position : Teaching Assistant (TA) <br>
  Prepared and evaluated assessment components for 240 students, including quizzes, assignments, and viva examinations, while assisting with course administration.
</div>


<h2>2023</h2>
<h3>Fall : Computer Systems</h3>
<div class="course-description">
  Professor Incharge: <a href="https://abhishek.people.iitgn.ac.in/">Abhishek Bichhawat</a>, 
  <a href="https://www.iitgn.ac.in/faculty/cse/sameer">Sameer G Kulkarni</a> <br>
  Position : Teaching Assistant (TA) <br>
  Graded assignments and assisted the professor run a class of 40 students smoothly.
</div>

<h3>Summer : World of Engineering</h3>
<div class="course-description">
  Professor Incharge: <a href="https://www.iitgn.ac.in/faculty/civil/fac-udit">Udit Bhatia</a> <br>
  Position : Teaching Assistant (TA) <br>
  Mentored a group of 30 students in the identification, conceptualization, and modeling of a prototype to address a real-world problem, fostering their problem-solving abilities and teamwork skills.
</div>

<h3>Spring : Probability, Statistics and Data Visualization</h3>
<div class="course-description">
  Professor Incharge: <a href="https://people.iitgn.ac.in/~shanmuga/">Shanmuganathan Raman</a> <br>
  Position : Teaching Assistant (TA) <br>
  Successfully guided over 30 students in Python libraries, including Numpy, Pandas, Matplotlib, Scipy, and Scikit-learn, enhancing their data visualization skills.
</div>


<h2>2022</h2>
<h3>Winter : Introduction to Computing</h3>
<div class="course-description">
  Professor Incharge: <a href="https://nipunbatra.github.io/">Nipun Batra</a>, 
  <a href="https://bkomarath.rbgo.in/">Balagopal Komarath</a> <br>
  Course Website: <a href="https://nipunbatra.github.io/comp22/">ES-112: Introduction to Computing</a> <br>
  Position : Teaching Assistant (TA) <br>
  Led a Python lab for 30 students, teaching them essential Python concepts, and helped manage logistics, invigilation, and quiz evaluation for a class of 300 students.
</div>
